- different methods to create a dataset
- reading dataset from external sources
- basic insights of dataset
- selection of data
  -  row wise selection
  - column wise selection
- data cleaning and manipulation

In [1]:
import pandas as pd

In [2]:
movies = {
    'title':['PK','RRR','I'],
    'year':[2018, 2022, 2020],
    'rating':[4.5,3.9,4.2]
    
}
df = pd.DataFrame(movies)
df

  title  year  rating
0    PK  2018     4.5
1   RRR  2022     3.9
2     I  2020     4.2

In [3]:
df = pd.read_csv('kc_house_data.csv')
df

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,263000018,20140521T000000,360000.0,3,2.50,1530,1131,3.0,0,0,...,8,1530,0,2009,0,98103,47.6993,-122.346,1530,1509
21609,6600060120,20150223T000000,400000.0,4,2.50,2310,5813,2.0,0,0,...,8,2310,0,2014,0,98146,47.5107,-122.362,1830,7200
21610,1523300141,20140623T000000,402101.0,2,0.75,1020,1350,2.0,0,0,...,7,1020,0,2009,0,98144,47.5944,-122.299,1020,2007
21611,291310100,20150116T000000,400000.0,3,2.50,1600,2388,2.0,0,0,...,8,1600,0,2004,0,98027,47.5345,-122.069,1410,1287
21612,1523300157,20141015T000000,325000.0,2,0.75,1020,1076,2.0,0,0,...,7,1020,0,2008,0,98144,47.5941,-122.299,1020,1357

In [4]:
df.head()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503

In [5]:
df = pd.read_csv('kc_house_data.csv')
df

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,263000018,20140521T000000,360000.0,3,2.50,1530,1131,3.0,0,0,...,8,1530,0,2009,0,98103,47.6993,-122.346,1530,1509
21609,6600060120,20150223T000000,400000.0,4,2.50,2310,5813,2.0,0,0,...,8,2310,0,2014,0,98146,47.5107,-122.362,1830,7200
21610,1523300141,20140623T000000,402101.0,2,0.75,1020,1350,2.0,0,0,...,7,1020,0,2009,0,98144,47.5944,-122.299,1020,2007
21611,291310100,20150116T000000,400000.0,3,2.50,1600,2388,2.0,0,0,...,8,1600,0,2004,0,98027,47.5345,-122.069,1410,1287
21612,1523300157,20141015T000000,325000.0,2,0.75,1020,1076,2.0,0,0,...,7,1020,0,2008,0,98144,47.5941,-122.299,1020,1357

In [6]:
df.tail()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
21608,263000018,20140521T000000,360000.0,3,2.50,1530,1131,3.0,0,0,...,8,1530,0,2009,0,98103,47.6993,-122.346,1530,1509
21609,6600060120,20150223T000000,400000.0,4,2.50,2310,5813,2.0,0,0,...,8,2310,0,2014,0,98146,47.5107,-122.362,1830,7200
21610,1523300141,20140623T000000,402101.0,2,0.75,1020,1350,2.0,0,0,...,7,1020,0,2009,0,98144,47.5944,-122.299,1020,2007
21611,291310100,20150116T000000,400000.0,3,2.50,1600,2388,2.0,0,0,...,8,1600,0,2004,0,98027,47.5345,-122.069,1410,1287
21612,1523300157,20141015T000000,325000.0,2,0.75,1020,1076,2.0,0,0,...,7,1020,0,2008,0,98144,47.5941,-122.299,1020,1357

In [7]:
df.head(5)

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503

In [8]:
df.sample()#pick one row randomly
df.sample(5)

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
10683,5451300105,20140720T000000,1050000.0,3,2.50,3470,12076,2.0,0,3,...,10,2560,910,1988,0,98040,47.5319,-122.238,3590,17677
9967,9541600060,20140807T000000,799000.0,5,2.75,2500,19783,1.0,0,3,...,8,2500,0,1959,0,98005,47.5938,-122.174,1700,15375
101,5200100125,20141027T000000,555000.0,3,2.00,1980,3478,1.5,0,0,...,7,1440,540,1929,0,98117,47.6775,-122.372,1610,3478
539,9485740340,20150310T000000,346900.0,4,2.50,1970,5106,2.0,0,0,...,8,1970,0,1999,0,98055,47.4490,-122.205,2230,5109
2733,4406000560,20150220T000000,278500.0,4,1.00,1540,8400,1.0,0,0,...,7,770,770,1971,0,98058,47.4278,-122.152,1520,9891

In [9]:
df.info()#concise summary

<class 'pandas.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             21613 non-null  int64
 1   date           21613 non-null  str
 2   price          21613 non-null  float64
 3   bedrooms       21613 non-null  int64
 4   bathrooms      21613 non-null  float64
 5   sqft_living    21613 non-null  int64
 6   sqft_lot       21613 non-null  int64
 7   floors         21613 non-null  float64
 8   waterfront     21613 non-null  int64
 9   view           21613 non-null  int64
 10  condition      21613 non-null  int64
 11  grade          21613 non-null  int64
 12  sqft_above     21613 non-null  int64
 13  sqft_basement  21613 non-null  int64
 14  yr_built       21613 non-null  int64
 15  yr_renovated   21613 non-null  int64
 16  zipcode        21613 non-null  int64
 17  lat            21613 non-null  float64
 18  long           21613 non-null  float64
 19  sqft_living15  21613 non-null  int64
 20  sqft_lot15     21613 non-null  int64
dtypes: float64(5), int64(15), str(1)
memory usage: 3.5 MB

In [10]:
df.isnull().sum()#check for null values

id               0
date             0
price            0
bedrooms         0
bathrooms        0
sqft_living      0
sqft_lot         0
floors           0
waterfront       0
view             0
condition        0
grade            0
sqft_above       0
sqft_basement    0
yr_built         0
yr_renovated     0
zipcode          0
lat              0
long             0
sqft_living15    0
sqft_lot15       0
dtype: int64

In [11]:
df.describe()#statistical summary

,id,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
count,2.161300e+04,2.161300e+04,21613.000000,21613.000000,21613.000000,2.161300e+04,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000
mean,4.580302e+09,5.400881e+05,3.370842,2.114757,2079.899736,1.510697e+04,1.494309,0.007542,0.234303,3.409430,7.656873,1788.390691,291.509045,1971.005136,84.402258,98077.939805,47.560053,-122.213896,1986.552492,12768.455652
std,2.876566e+09,3.671272e+05,0.930062,0.770163,918.440897,4.142051e+04,0.539989,0.086517,0.766318,0.650743,1.175459,828.090978,442.575043,29.373411,401.679240,53.505026,0.138564,0.140828,685.391304,27304.179631
min,1.000102e+06,7.500000e+04,0.000000,0.000000,290.000000,5.200000e+02,1.000000,0.000000,0.000000,1.000000,1.000000,290.000000,0.000000,1900.000000,0.000000,98001.000000,47.155900,-122.519000,399.000000,651.000000
25%,2.123049e+09,3.219500e+05,3.000000,1.750000,1427.000000,5.040000e+03,1.000000,0.000000,0.000000,3.000000,7.000000,1190.000000,0.000000,1951.000000,0.000000,98033.000000,47.471000,-122.328000,1490.000000,5100.000000
50%,3.904930e+09,4.500000e+05,3.000000,2.250000,1910.000000,7.618000e+03,1.500000,0.000000,0.000000,3.000000,7.000000,1560.000000,0.000000,1975.000000,0.000000,98065.000000,47.571800,-122.230000,1840.000000,7620.000000
75%,7.308900e+09,6.450000e+05,4.000000,2.500000,2550.000000,1.068800e+04,2.000000,0.000000,0.000000,4.000000,8.000000,2210.000000,560.000000,1997.000000,0.000000,98118.000000,47.678000,-122.125000,2360.000000,10083.000000
max,9.900000e+09,7.700000e+06,33.000000,8.000000,13540.000000,1.651359e+06,3.500000,1.000000,4.000000,5.000000,13.000000,9410.000000,4820.000000,2015.000000,2015.000000,98199.000000,47.777600,-121.315000,6210.000000,871200.000000

In [12]:
df.columns

Index(['id', 'date', 'price', 'bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long', 'sqft_living15', 'sqft_lot15'],
      dtype='str')

In [13]:
df.columns.tolist()

['id',
 'date',
 'price',
 'bedrooms',
 'bathrooms',
 'sqft_living',
 'sqft_lot',
 'floors',
 'waterfront',
 'view',
 'condition',
 'grade',
 'sqft_above',
 'sqft_basement',
 'yr_built',
 'yr_renovated',
 'zipcode',
 'lat',
 'long',
 'sqft_living15',
 'sqft_lot15']

- row wise selction
  - iloc : index based selection
  - loc : label based selection
- column wise selection
  - single column selection
     - dictionary like
     - object like
  - multiple column selection
     -dictionarym like

In [14]:
df.iloc[5]
df.iloc[-7]

id                    7936000429
date             20150326T000000
price                  1007500.0
bedrooms                       4
bathrooms                    3.5
sqft_living                 3510
sqft_lot                    7200
floors                       2.0
waterfront                     0
view                           0
condition                      3
grade                          9
sqft_above                  2600
sqft_basement                910
yr_built                    2009
yr_renovated                   0
zipcode                    98136
lat                      47.5537
long                    -122.398
sqft_living15               2050
sqft_lot15                  6200
Name: 21606, dtype: object

In [15]:
df.iloc[1:6]#end range is exclusive
df.iloc[1:11:3]

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503
7,2008000270,20150115T000000,291850.0,3,1.50,1060,9711,1.0,0,0,...,7,1060,0,1963,0,98198,47.4095,-122.315,1650,9711
10,1736800520,20150403T000000,662500.0,3,2.50,3560,9796,1.0,0,0,...,8,1860,1700,1965,0,98007,47.6007,-122.145,2210,8925

In [16]:
df.iloc[[3,5,7,10,9]]#pick specific rows

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
3,2487200875,20141209T000000,604000.0,4,3.0,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
5,7237550310,20140512T000000,1225000.0,4,4.5,5420,101930,1.0,0,0,...,11,3890,1530,2001,0,98053,47.6561,-122.005,4760,101930
7,2008000270,20150115T000000,291850.0,3,1.5,1060,9711,1.0,0,0,...,7,1060,0,1963,0,98198,47.4095,-122.315,1650,9711
10,1736800520,20150403T000000,662500.0,3,2.5,3560,9796,1.0,0,0,...,8,1860,1700,1965,0,98007,47.6007,-122.145,2210,8925
9,3793500160,20150312T000000,323000.0,3,2.5,1890,6560,2.0,0,0,...,7,1890,0,2003,0,98038,47.3684,-122.031,2390,7570

In [17]:
df.iloc[[3,4,7]],[[5,6,]]#pick specific rows and columns

(           id             date     price  bedrooms  bathrooms  sqft_living  \
 3  2487200875  20141209T000000  604000.0         4        3.0         1960
 4  1954400510  20150218T000000  510000.0         3        2.0         1680
 7  2008000270  20150115T000000  291850.0         3        1.5         1060

    sqft_lot  floors  waterfront  view  ...  grade  sqft_above  sqft_basement  \
 3      5000     1.0           0     0  ...      7        1050            910
 4      8080     1.0           0     0  ...      8        1680              0
 7      9711     1.0           0     0  ...      7        1060              0

    yr_built  yr_renovated  zipcode      lat     long  sqft_living15  \
 3      1965             0    98136  47.5208 -122.393           1360
 4      1987             0    98074  47.6168 -122.045           1800
 7      1963             0    98198  47.4095 -122.315           1650

    sqft_lot15
 3        5000
 4        7503
 7        9711

 [3 rows x 21 columns],
 [[5, 6]])

In [18]:
df = df.set_index('id')#set index to id column
df

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
id,,,,,,,,,,,,,,,,,,,,
7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,3,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,3,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,5,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,3,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263000018,20140521T000000,360000.0,3,2.50,1530,1131,3.0,0,0,3,8,1530,0,2009,0,98103,47.6993,-122.346,1530,1509
6600060120,20150223T000000,400000.0,4,2.50,2310,5813,2.0,0,0,3,8,2310,0,2014,0,98146,47.5107,-122.362,1830,7200
1523300141,20140623T000000,402101.0,2,0.75,1020,1350,2.0,0,0,3,7,1020,0,2009,0,98144,47.5944,-122.299,1020,2007
291310100,20150116T000000,400000.0,3,2.50,1600,2388,2.0,0,0,3,8,1600,0,2004,0,98027,47.5345,-122.069,1410,1287
1523300157,20141015T000000,325000.0,2,0.75,1020,1076,2.0,0,0,3,7,1020,0,2008,0,98144,47.5941,-122.299,1020,1357

In [19]:
df.loc[7129300520]

date             20141013T000000
price                   221900.0
bedrooms                       3
bathrooms                    1.0
sqft_living                 1180
sqft_lot                    5650
floors                       1.0
waterfront                     0
view                           0
condition                      3
grade                          7
sqft_above                  1180
sqft_basement                  0
yr_built                    1955
yr_renovated                   0
zipcode                    98178
lat                      47.5112
long                    -122.257
sqft_living15               1340
sqft_lot15                  5650
Name: 7129300520, dtype: object

In [20]:
df.loc[7129300520:1954400510]#end range is inclusive

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
id,,,,,,,,,,,,,,,,,,,,
7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,3,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,3,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,5,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,3,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503

In [21]:
df['price']

id
7129300520    221900.0
6414100192    538000.0
5631500400    180000.0
2487200875    604000.0
1954400510    510000.0
                ...
263000018     360000.0
6600060120    400000.0
1523300141    402101.0
291310100     400000.0
1523300157    325000.0
Name: price, Length: 21613, dtype: float64

In [22]:
df.get('price')

id
7129300520    221900.0
6414100192    538000.0
5631500400    180000.0
2487200875    604000.0
1954400510    510000.0
                ...
263000018     360000.0
6600060120    400000.0
1523300141    402101.0
291310100     400000.0
1523300157    325000.0
Name: price, Length: 21613, dtype: float64

In [23]:
df[['price','bedrooms','bathrooms']]

               price  bedrooms  bathrooms
id
7129300520  221900.0         3       1.00
6414100192  538000.0         3       2.25
5631500400  180000.0         2       1.00
2487200875  604000.0         4       3.00
1954400510  510000.0         3       2.00
...              ...       ...        ...
263000018   360000.0         3       2.50
6600060120  400000.0         4       2.50
1523300141  402101.0         2       0.75
291310100   400000.0         3       2.50
1523300157  325000.0         2       0.75

[21613 rows x 3 columns]

In [24]:
df.loc[[1954400510	,5631500400]]

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
id,,,,,,,,,,,,,,,,,,,,
1954400510,20150218T000000,510000.0,3,2.0,1680,8080,1.0,0,0,3,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503
5631500400,20150225T000000,180000.0,2,1.0,770,10000,1.0,0,0,3,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062

DATA CLEANING 

- dropping rows and column
- renaming column names
- changing data types of a column
- dropping missing values
- handling missing values
- checking duplicates
- dropping duplicates
- checking unique values
- count of unique values
- frequency count of a value
- sorting values

In [25]:
df = df.drop(columns=['sqft_living15','sqft_lot15'])#drop columns
df.columns

Index(['date', 'price', 'bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot',
       'floors', 'waterfront', 'view', 'condition', 'grade', 'sqft_above',
       'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode', 'lat', 'long'],
      dtype='str')

In [26]:
df.drop(labels=[7129300520],inplace=True)#drop row with id 7129300520
df.head

<bound method NDFrame.head of                        date      price  bedrooms  bathrooms  sqft_living  \
id
6414100192  20141209T000000   538000.0         3       2.25         2570
5631500400  20150225T000000   180000.0         2       1.00          770
2487200875  20141209T000000   604000.0         4       3.00         1960
1954400510  20150218T000000   510000.0         3       2.00         1680
7237550310  20140512T000000  1225000.0         4       4.50         5420
...                     ...        ...       ...        ...          ...
263000018   20140521T000000   360000.0         3       2.50         1530
6600060120  20150223T000000   400000.0         4       2.50         2310
1523300141  20140623T000000   402101.0         2       0.75         1020
291310100   20150116T000000   400000.0         3       2.50         1600
1523300157  20141015T000000   325000.0         2       0.75         1020

            sqft_lot  floors  waterfront  view  condition  grade  sqft_above  \
id
6414100192      7242     2.0           0     0          3      7        2170
5631500400     10000     1.0           0     0          3      6         770
2487200875      5000     1.0           0     0          5      7        1050
1954400510      8080     1.0           0     0          3      8        1680
7237550310    101930     1.0           0     0          3     11        3890
...              ...     ...         ...   ...        ...    ...         ...
263000018       1131     3.0           0     0          3      8        1530
6600060120      5813     2.0           0     0          3      8        2310
1523300141      1350     2.0           0     0          3      7        1020
291310100       2388     2.0           0     0          3      8        1600
1523300157      1076     2.0           0     0          3      7        1020

            sqft_basement  yr_built  yr_renovated  zipcode      lat     long
id
6414100192            400      1951          1991    98125  47.7210 -122.319
5631500400              0      1933             0    98028  47.7379 -122.233
2487200875            910      1965             0    98136  47.5208 -122.393
1954400510              0      1987             0    98074  47.6168 -122.045
7237550310           1530      2001             0    98053  47.6561 -122.005
...                   ...       ...           ...      ...      ...      ...
263000018               0      2009             0    98103  47.6993 -122.346
6600060120              0      2014             0    98146  47.5107 -122.362
1523300141              0      2009             0    98144  47.5944 -122.299
291310100               0      2004             0    98027  47.5345 -122.069
1523300157              0      2008             0    98144  47.5941 -122.299

[21612 rows x 18 columns]>

In [27]:
df = df.astype({'bedrooms':'float64'})
df

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long
id,,,,,,,,,,,,,,,,,,
6414100192,20141209T000000,538000.0,3.0,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,1991,98125,47.7210,-122.319
5631500400,20150225T000000,180000.0,2.0,1.00,770,10000,1.0,0,0,3,6,770,0,1933,0,98028,47.7379,-122.233
2487200875,20141209T000000,604000.0,4.0,3.00,1960,5000,1.0,0,0,5,7,1050,910,1965,0,98136,47.5208,-122.393
1954400510,20150218T000000,510000.0,3.0,2.00,1680,8080,1.0,0,0,3,8,1680,0,1987,0,98074,47.6168,-122.045
7237550310,20140512T000000,1225000.0,4.0,4.50,5420,101930,1.0,0,0,3,11,3890,1530,2001,0,98053,47.6561,-122.005
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263000018,20140521T000000,360000.0,3.0,2.50,1530,1131,3.0,0,0,3,8,1530,0,2009,0,98103,47.6993,-122.346
6600060120,20150223T000000,400000.0,4.0,2.50,2310,5813,2.0,0,0,3,8,2310,0,2014,0,98146,47.5107,-122.362
1523300141,20140623T000000,402101.0,2.0,0.75,1020,1350,2.0,0,0,3,7,1020,0,2009,0,98144,47.5944,-122.299
291310100,20150116T000000,400000.0,3.0,2.50,1600,2388,2.0,0,0,3,8,1600,0,2004,0,98027,47.5345,-122.069
1523300157,20141015T000000,325000.0,2.0,0.75,1020,1076,2.0,0,0,3,7,1020,0,2008,0,98144,47.5941,-122.299

In [28]:
renamed_cols = {
    'lat': 'latitude',
    'long': 'longitude',
}

In [29]:
df=df.rename(columns=renamed_cols)
df.columns

Index(['date', 'price', 'bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot',
       'floors', 'waterfront', 'view', 'condition', 'grade', 'sqft_above',
       'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode', 'latitude',
       'longitude'],
      dtype='str')

In [30]:
import seaborn as sns
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

- When a column has <40% missing values of the data, then we simply remove that  column
- When a column has >40% missing values of data, then we handle those missing values means we replace those missing values with any number
    - there are teo type of columns in any dataset - CATAGORICAL & NUMERICAL
    - When the column is numerical, we always repalce the null values with the column mean(average)
    - When the column is categorical, we always replace the null values with most frequent(mode) values

In [31]:
titanic = sns.load_dataset('titanic')
titanic.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [32]:
titanic = titanic.dropna(subset=['embarked'])#drop rows where the'embarked' column has null values
titanic.isnull().sum()#gives the count of null values in each column

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         0
class            0
who              0
adult_male       0
deck           688
embark_town      0
alive            0
alone            0
dtype: int64

In [33]:
avg_age = round(titanic['age'].mean())#calculate the average age of passengers in the titanic dataset
print(avg_age)

30

In [34]:
#replace null values with avg_age
titanic['age']=titanic['age'].fillna(avg_age)#replace null values in the 'age' column with avg_age
titanic.isnull().sum()

survived         0
pclass           0
sex              0
age              0
sibsp            0
parch            0
fare             0
embarked         0
class            0
who              0
adult_male       0
deck           688
embark_town      0
alive            0
alone            0
dtype: int64

In [35]:
#checking duplicate values
duplicates = titanic[titanic.duplicated()]
print(duplicates)

     survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
47          1       3  female  30.0      0      0   7.7500        Q   Third
76          0       3    male  30.0      0      0   7.8958        S   Third
77          0       3    male  30.0      0      0   8.0500        S   Third
87          0       3    male  30.0      0      0   8.0500        S   Third
95          0       3    male  30.0      0      0   8.0500        S   Third
..        ...     ...     ...   ...    ...    ...      ...      ...     ...
870         0       3    male  26.0      0      0   7.8958        S   Third
877         0       3    male  19.0      0      0   7.8958        S   Third
878         0       3    male  30.0      0      0   7.8958        S   Third
884         0       3    male  25.0      0      0   7.0500        S   Third
886         0       2    male  27.0      0      0  13.0000        S  Second

       who  adult_male deck  embark_town alive  alone
47   woman       False  NaN   Queenstown   yes   True
76     man        True  NaN  Southampton    no   True
77     man        True  NaN  Southampton    no   True
87     man        True  NaN  Southampton    no   True
95     man        True  NaN  Southampton    no   True
..     ...         ...  ...          ...   ...    ...
870    man        True  NaN  Southampton    no   True
877    man        True  NaN  Southampton    no   True
878    man        True  NaN  Southampton    no   True
884    man        True  NaN  Southampton    no   True
886    man        True  NaN  Southampton    no   True

[113 rows x 15 columns]

In [36]:
#dropping duplicates
titanic.drop_duplicates

<bound method DataFrame.drop_duplicates of      survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third
1           1       1  female  38.0      1      0  71.2833        C   First
2           1       3  female  26.0      0      0   7.9250        S   Third
3           1       1  female  35.0      1      0  53.1000        S   First
4           0       3    male  35.0      0      0   8.0500        S   Third
..        ...     ...     ...   ...    ...    ...      ...      ...     ...
886         0       2    male  27.0      0      0  13.0000        S  Second
887         1       1  female  19.0      0      0  30.0000        S   First
888         0       3  female  30.0      1      2  23.4500        S   Third
889         1       1    male  26.0      0      0  30.0000        C   First
890         0       3    male  32.0      0      0   7.7500        Q   Third

       who  adult_male deck  embark_town alive  alone
0      man        True  NaN  Southampton    no  False
1    woman       False    C    Cherbourg   yes  False
2    woman       False  NaN  Southampton   yes   True
3    woman       False    C  Southampton   yes  False
4      man        True  NaN  Southampton    no   True
..     ...         ...  ...          ...   ...    ...
886    man        True  NaN  Southampton    no   True
887  woman       False    B  Southampton   yes   True
888  woman       False  NaN  Southampton    no  False
889    man        True    C    Cherbourg   yes   True
890    man        True  NaN   Queenstown    no   True

[889 rows x 15 columns]>

In [37]:
titanic['age'].unique()

array([22.  , 38.  , 26.  , 35.  , 30.  , 54.  ,  2.  , 27.  , 14.  ,
        4.  , 58.  , 20.  , 39.  , 55.  , 31.  , 34.  , 15.  , 28.  ,
        8.  , 19.  , 40.  , 66.  , 42.  , 21.  , 18.  ,  3.  ,  7.  ,
       49.  , 29.  , 65.  , 28.5 ,  5.  , 11.  , 45.  , 17.  , 32.  ,
       16.  , 25.  ,  0.83, 33.  , 23.  , 24.  , 46.  , 59.  , 71.  ,
       37.  , 47.  , 14.5 , 70.5 , 32.5 , 12.  ,  9.  , 36.5 , 51.  ,
       55.5 , 40.5 , 44.  ,  1.  , 61.  , 56.  , 50.  , 36.  , 45.5 ,
       20.5 , 62.  , 41.  , 52.  , 63.  , 23.5 ,  0.92, 43.  , 60.  ,
       10.  , 64.  , 13.  , 48.  ,  0.75, 53.  , 57.  , 80.  , 70.  ,
       24.5 ,  6.  ,  0.67, 30.5 ,  0.42, 34.5 , 74.  ])

In [38]:
#frequence of values in a categorical column
titanic['embark_town'].value_counts()

embark_town
Southampton    644
Cherbourg      168
Queenstown      77
Name: count, dtype: int64

In [39]:
titanic['embark_town'].value_counts().idxmin()

'Queenstown'

In [40]:
titanic['embark_town'].value_counts().idxmax()

'Southampton'

In [41]:
titanic.sort_index()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,30.0,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [42]:
#adding a new column
titanic = titanic.assign(discount =titanic['fare']*0.10)
titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,discount
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,0.72500
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,7.12833
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,0.79250
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,5.31000
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,0.80500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True,1.30000
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True,3.00000
888,0,3,female,30.0,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False,2.34500
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True,3.00000
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True,0.77500

In [43]:
titanic['fare']=titanic['fare'].apply(lambda x:x*1.05)
titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,discount
0,0,3,male,22.0,1,0,7.612500,S,Third,man,True,NaN,Southampton,no,False,0.72500
1,1,1,female,38.0,1,0,74.847465,C,First,woman,False,C,Cherbourg,yes,False,7.12833
2,1,3,female,26.0,0,0,8.321250,S,Third,woman,False,NaN,Southampton,yes,True,0.79250
3,1,1,female,35.0,1,0,55.755000,S,First,woman,False,C,Southampton,yes,False,5.31000
4,0,3,male,35.0,0,0,8.452500,S,Third,man,True,NaN,Southampton,no,True,0.80500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.650000,S,Second,man,True,NaN,Southampton,no,True,1.30000
887,1,1,female,19.0,0,0,31.500000,S,First,woman,False,B,Southampton,yes,True,3.00000
888,0,3,female,30.0,1,2,24.622500,S,Third,woman,False,NaN,Southampton,no,False,2.34500
889,1,1,male,26.0,0,0,31.500000,C,First,man,True,C,Cherbourg,yes,True,3.00000
890,0,3,male,32.0,0,0,8.137500,Q,Third,man,True,NaN,Queenstown,no,True,0.77500

In [44]:
titanic['embarked']=titanic['embarked'].map({
    "S":"Southampton",
    "C":"Cherbourg",
    "Q":"Queenstown"
})
titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,discount
0,0,3,male,22.0,1,0,7.612500,Southampton,Third,man,True,NaN,Southampton,no,False,0.72500
1,1,1,female,38.0,1,0,74.847465,Cherbourg,First,woman,False,C,Cherbourg,yes,False,7.12833
2,1,3,female,26.0,0,0,8.321250,Southampton,Third,woman,False,NaN,Southampton,yes,True,0.79250
3,1,1,female,35.0,1,0,55.755000,Southampton,First,woman,False,C,Southampton,yes,False,5.31000
4,0,3,male,35.0,0,0,8.452500,Southampton,Third,man,True,NaN,Southampton,no,True,0.80500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.650000,Southampton,Second,man,True,NaN,Southampton,no,True,1.30000
887,1,1,female,19.0,0,0,31.500000,Southampton,First,woman,False,B,Southampton,yes,True,3.00000
888,0,3,female,30.0,1,2,24.622500,Southampton,Third,woman,False,NaN,Southampton,no,False,2.34500
889,1,1,male,26.0,0,0,31.500000,Cherbourg,First,man,True,C,Cherbourg,yes,True,3.00000
890,0,3,male,32.0,0,0,8.137500,Queenstown,Third,man,True,NaN,Queenstown,no,True,0.77500

In [ ]:
titanic.groupby("embarked")["fare"].mean()

embarked
Cherbourg      62.951851
Queenstown     13.939831
Southampton    28.433802
Name: fare, dtype: float64

In [49]:
titanic.groupby("sex")["fare"].max()

sex
female    537.94566
male      537.94566
Name: fare, dtype: float64

In [50]:
#data filtering
titanic[titanic["survived"]==0]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,discount
0,0,3,male,22.0,1,0,7.612500,Southampton,Third,man,True,NaN,Southampton,no,False,0.72500
4,0,3,male,35.0,0,0,8.452500,Southampton,Third,man,True,NaN,Southampton,no,True,0.80500
5,0,3,male,30.0,0,0,8.881215,Queenstown,Third,man,True,NaN,Queenstown,no,True,0.84583
6,0,1,male,54.0,0,0,54.455625,Southampton,First,man,True,E,Southampton,no,True,5.18625
7,0,3,male,2.0,3,1,22.128750,Southampton,Third,child,False,NaN,Southampton,no,False,2.10750
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
884,0,3,male,25.0,0,0,7.402500,Southampton,Third,man,True,NaN,Southampton,no,True,0.70500
885,0,3,female,39.0,0,5,30.581250,Queenstown,Third,woman,False,NaN,Queenstown,no,False,2.91250
886,0,2,male,27.0,0,0,13.650000,Southampton,Second,man,True,NaN,Southampton,no,True,1.30000
888,0,3,female,30.0,1,2,24.622500,Southampton,Third,woman,False,NaN,Southampton,no,False,2.34500
890,0,3,male,32.0,0,0,8.137500,Queenstown,Third,man,True,NaN,Queenstown,no,True,0.77500

In [51]:
titanic[titanic['sex']=="female"]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,discount
1,1,1,female,38.0,1,0,74.847465,Cherbourg,First,woman,False,C,Cherbourg,yes,False,7.12833
2,1,3,female,26.0,0,0,8.321250,Southampton,Third,woman,False,NaN,Southampton,yes,True,0.79250
3,1,1,female,35.0,1,0,55.755000,Southampton,First,woman,False,C,Southampton,yes,False,5.31000
8,1,3,female,27.0,0,2,11.689965,Southampton,Third,woman,False,NaN,Southampton,yes,False,1.11333
9,1,2,female,14.0,1,0,31.574340,Cherbourg,Second,child,False,NaN,Cherbourg,yes,False,3.00708
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
880,1,2,female,25.0,0,1,27.300000,Southampton,Second,woman,False,NaN,Southampton,yes,False,2.60000
882,0,3,female,22.0,0,0,11.042535,Southampton,Third,woman,False,NaN,Southampton,no,True,1.05167
885,0,3,female,39.0,0,5,30.581250,Queenstown,Third,woman,False,NaN,Queenstown,no,False,2.91250
887,1,1,female,19.0,0,0,31.500000,Southampton,First,woman,False,B,Southampton,yes,True,3.00000
888,0,3,female,30.0,1,2,24.622500,Southampton,Third,woman,False,NaN,Southampton,no,False,2.34500